#!/bin/csh -f
#
# Run cmake with reasonable defaults. Why make the user do all these steps?
#

###source @env/g5_modules # to be sure
cmake -B build -S . --install-prefix `pwd`/install # -DCMAKE_BUILD_TYPE=Debug
cmake --build build --target install -j 6
