#!/bin/csh -f
#
# Run cmake with reasonable defaults. Why make the user do all these steps?
#

###source @env/g5_modules # to be sure
mkdir -p build
cd build
##cmake .. -DBASEDIR=$BASEDIR/`uname -s` \
cmake .. -DBASEDIR=$BASEDIR/`uname -s` \
         -DCMAKE_Fortran_COMPILER=gfortran \
         -DCMAKE_INSTALL_PREFIX=../install
      
